### ISSUE TITLE
WARNING: No "type" specified

### ISSUE THREAD

**Issue by mes3yd** [Rebilly/ReDoc#653] opened 2018-09-24 07:15 UTC
This happens when referencing a path parameter. It expects a type to be on the parameter itself and not as a child of schema:

Works:
```yaml
service_id:
  name: service_id
  in: path
  required: true
  type: integer
```
Doesn't work:
```yaml
service_id:
  name: service_id
  in: path
  required: true
  schema:
    type: integer
```

The reference can be in another file or simply `#/components/parameters/service_id`.
Since it recognizes no type and defaults to object, on cannot fill in any parameters to test.

**Comment by RomanGotsiy** [comment] 2018-09-24 08:28
@mes3yd could you also show a context you are referencing your parameter from?
Thanks

**Comment by mes3yd** [comment] 2018-09-24 19:10
I built a container using `redoc-cli` and everything works now, but the standalone (.19 and .22) didn't work. So from the top of my head a minimum would be:

```yaml
openapi: 3.0.0
info:
  title: Example
  description: Example API
  version: 2.0.5
servers:
  http://example.com/api/v2
paths:
  /services/{service_id}/
    parameters:
      - $ref: '#/components/parameters/service_id'
components:
  parameters:
    service_id:
      name: service_id
      in: path
      required: true
      schema:
        type: integer
```

**Comment by RomanGotsiy** [comment] 2018-10-05 13:03
I just tried it and can't reproduce on the latest alpha:

```yaml
openapi: 3.0.0
info:
  title: Example
  description: Example API
  version: 2.0.5
servers:
  - url: http://example.com/api/v2
paths:
  /services/{service_id}/:
    put:
      summary: test
      parameters:
      - $ref: '#/components/parameters/service_id'
components:
  parameters:
    service_id:
      name: service_id
      in: path
      required: true
      schema:
        type: integer

```

Closing as can't reproduce.
Feel free to continue discussion here

**Closed by RomanGotsiy** 2018-10-05 13:03 UTC
