### ISSUE TITLE
master branch not compile

### ISSUE THREAD

**Issue by ilMattion** [Rebilly/ReDoc#402] opened 2018-01-09 16:10 UTC
Hi,
when I try to execute locally ReDoc I obtain this errors:

> redoc@1.19.3 start C:\Source\ReDoc
> webpack-dev-server --port 8081 --config build/webpack.dev.js --content-base demo

> Project is running at http://localhost:8081/
> webpack output is served from /
> Content not from webpack is served from C:\Source\ReDoc\demo
> 
> [at-loader] Using typescript@2.6.2 from typescript and "tsconfig.json" from C:\Source\ReDoc/tsconfig.json (in a forked process).
> 
> 
> [at-loader] Checking started in a separate process...
> 
> webpack: Compiled successfully.
> 
> [at-loader] Checking finished with 7 errors
> [at-loader] ./lib/bootstrap.ts:4:36
>     TS2307: Cannot find module '../compiled/lib/app.module.ngfactory'.
> 
> [at-loader] ./lib/services/menu.service.ts:393:25
>     TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "C:/Source/ReDoc/node_modules/slugify/index"' has no compatible call signatures.
> 
> [at-loader] ./lib/services/search.service.ts:89:23
>     TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "C:/Source/ReDoc/node_modules/slugify/index"' has no compatible call signatures.
> 
> [at-loader] ./lib/utils/md-renderer.ts:64:16
>     TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "C:/Source/ReDoc/node_modules/slugify/index"' has no compatible call signatures.
> 
> [at-loader] ./lib/utils/spec-manager.ts:74:27
>     TS2339: Property 'protocol' does not exist on type '{}'.
> 
> [at-loader] ./lib/utils/spec-manager.ts:74:47
>     TS2339: Property 'protocol' does not exist on type '{}'.
> 
> [at-loader] ./lib/utils/spec-manager.ts:82:46
>     TS2339: Property 'host' does not exist on type '{}'.

I've not edit files.

**Comment by RomanGotsiy** [comment] 2018-01-21 19:06
This is a duplicate of #405. Let's track it there

**Closed by RomanGotsiy** 2018-01-21 19:06 UTC
