### ISSUE TITLE
ReDoc doesn't resolve relative file URL to swagger spec

### ISSUE THREAD

**Issue by shreyas-agnihotri** [Rebilly/ReDoc#390] opened 2017-12-12 20:10 UTC
redoc-standalone.js and swagger.yaml are in the same directory. HTML looks like this:

```
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- link rel="stylesheet" href="main.css" -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <redoc scroll-y-offset="body > nav" spec-url='swagger.yaml' lazy-rendering untrusted-spec></redoc>
    <script src="redoc.standalone.js"></script>
  </body>
</html>
```

I get an exception when trying to load the html.
Unable to resolve $ref pointer "file:///Users/max/Desktop/ReDoc/demo/swagger.yaml"

Seems like local file URLs are not resolved correctly.

**Comment by bartfeenstra** [comment] 2017-12-13 18:33
What happens when you go to file:///Users/max/Desktop/ReDoc/demo/swagger.yaml in your browser directly?

**Comment by shreyas-agnihotri** [comment] 2017-12-13 22:46
> What happens when you go to file:///Users/max/Desktop/ReDoc/demo/swagger.yaml in your browser directly?

I see the contents of YAML file in browser.

**Comment by drewish** [comment] 2017-12-14 13:24
Curious what you mean by:
> Unable to resolve $ref pointer

Do you mean it won't follow a `$ref` from inside you're swagger.yaml file to another file?

**Comment by shreyas-agnihotri** [comment] 2017-12-14 15:02
> Unable to resolve $ref pointer

So my swagger.yaml doesn't have any $ref. That's the error message string being thrown by ReDoc.

I must clarify that I am not running any web server. I just have the swagger.yaml and index.html (with the HTML code above) in the same directory. I am then trying to open index.html in a browser by double-clicking on it.

**Comment by RomanGotsiy** [comment] 2017-12-14 15:14
Hey guys. This is a duplicate of https://github.com/Rebilly/ReDoc/issues/149

I think I will finally fix in the upcoming alpha release.

**Closed by RomanGotsiy** 2017-12-14 15:14 UTC
