### ISSUE TITLE
Strange Icons

### ISSUE THREAD

**Issue by KyleGobel** [Rebilly/ReDoc#346] opened 2017-09-22 17:51 UTC
I'm not sure what I'm missing or why things are rendering like this.

Thought this maybe a common one.

Everything looks fine except when responses don't have a schema.

Example:

![image](https://user-images.githubusercontent.com/4460054/30757484-e0412d40-9f9c-11e7-8f42-7112dbde81cb.png)

An example css class that makes that:
```
zippy-empty[_ngcontent-grp-11] .zippy-indicator[_ngcontent-grp-11]:before {
    content: "â€”";
    font-weight: bold;
}
```

Not sure why this happening though (minus sign "-" being switched with whatever that symbol is)

**Comment by RomanGotsiy** [comment] 2017-09-23 06:05
Duplicate of https://github.com/Rebilly/ReDoc/issues/213 and https://github.com/Rebilly/ReDoc/issues/29

tl;dr
Just add `<meta charset="utf-8"/>` to your html

**Closed by RomanGotsiy** 2017-09-23 06:05 UTC
