### ISSUE TITLE
The padding is reset to default when clicking a navigation tab

### ISSUE THREAD

**Issue by ksrh** [Rebilly/ReDoc#821] opened 2019-02-25 09:47 UTC
Hello!

I use ReDoc to display several swagger json files, and I have an issue with padding.
Padding is set to 10 px, with a theme option `sectionVertical`,  as described [here](https://github.com/Rebilly/ReDoc/issues/623#issuecomment-427339621)

<details><summary>Here are the ReDoc options:</summary>

```
<script>
--
  | // list of APIS
  | var apis = [{name:"API1", url:"example.com/swagger1"},{name:"API2", url:"example.com/swagger2"}];
  | // initially render first API
  | Redoc.init(apis[0].url,
  | {
  | "theme":{
  | "spacing":
  | {
  | "sectionVertical":10
  | }
  | }
  | }
  | );
  | function onClick() {
  | var url = this.getAttribute('data-link');
  | Redoc.init(url);
  | }
  | // dynamically building navigation items
  | var $list = document.getElementById('links_container');
  | apis.forEach(function(api) {
  | var $listitem = document.createElement('li');
  | $listitem.setAttribute('data-link', api.url);
  | $listitem.innerText = api.name;
  | $listitem.addEventListener('click', onClick);
  | $list.appendChild($listitem);
  | });
  | </script>
```
</details>
</br>

Initially, the padding is 10px as defined:
![scr1](https://user-images.githubusercontent.com/29098236/53327786-90458c80-38f9-11e9-8a53-f9690fc77243.png)

But after clicking a tab on the navigation bar the padding resets to default 40px:
![scr2](https://user-images.githubusercontent.com/29098236/53327863-c2ef8500-38f9-11e9-8db2-586d04579980.png)

**Comment by RomanGotsiy** [comment] 2019-02-25 10:02
I think theme is reset by default by this `Redoc.init(url);`.

Try `Redoc.init(url, {theme: ...});` in `onClick` handler

**Comment by RomanGotsiy** [comment] 2019-02-26 08:04
Closing it as I'm sure this is caused by reinitializing ReDoc without theme option which involves default theme.

**Closed by RomanGotsiy** 2019-02-26 08:04 UTC

**Comment by ksrh** [comment] 2019-02-26 12:00
that works, thanks!
