### ISSUE TITLE
links to tag dont work with tag groups

### ISSUE THREAD

**Issue by callumdt** [Rebilly/ReDoc#273] opened 2017-05-24 11:05 UTC
Hi, I have been using links in descriptions to other tags so that users can jump to other places on the page. I then added tag grouping to better display related tags in the side menu however this seems to have broken links in descriptions which now only seem able to jump to the top of the page. using `[imalink](#/tag/User-Login)` no longer jumps to my 'User Login' tag, but to the top of the page.

in the url bar the correct tag link is displayed and then immediately jumps the first tag (an introduction tag that is part of the info.description).

Is this a bug or am i doing something wrong?

**Comment by RomanGotsiy** [comment] 2017-05-24 12:57
@callumdt this is a bug. Thanks for reporting

**Comment by RomanGotsiy** [comment] 2017-06-02 07:31
@callumdt I just checked it more careful about that and probably that's not a bug.

Do you link to tags which are groups? If yes, this is not supported and a bit difficult to support. Instead just update your links to reference the first tag from the group. E.g. on the demo there is tag group `General`. The following link won't work: `#/tag/General` but this `#tag/pet` works just fine (where `pet` is the first tag in the tag group)

**Comment by callumdt** [comment] 2017-06-07 13:54
So it looks like the slash preceding the tag in the path causes the behaviour described when using the tag groupings.

i.e. `[this link right here](#/tag/pet)` will link to the `pet` tag until the `pet` tag is part of the `x-tagGroups` `General` group in which case only `[this link right here](#tag/pet)` will give you the expected behaviour of jumping to the `pet` tag on the page.

I was using v1.8 and upgraded to v1.16 when i saw this change in behaviour, but knowing how this now works means that i can work around and update my links.

**Comment by RomanGotsiy** [comment] 2017-08-17 07:53
Awesome,

Closing this issue.

Feel free to continue conversation though!

**Closed by RomanGotsiy** 2017-08-17 07:53 UTC
Labels: bug
