### ISSUE TITLE
Show Authorization in Request sample

### ISSUE THREAD

**Issue by raderio** [Rebilly/ReDoc#908] opened 2019-05-09 07:49 UTC
Please add support to show the Authorization header example in Request sample.
An example can be https://developer.paypal.com/docs/api/payments/v1/#payment_create
```
curl -v -X POST https://api.sandbox.paypal.com/v1/payments/payment \
-H "Content-Type: application/json" \
-H "Authorization: Bearer Access-Token" \
-d '{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  }
}'
```

**Comment by RomanGotsiy** [comment] 2019-05-09 12:09
Duplicate of #15?

Curl samples are not supported yet.

ReDoc shows only **payload sample** ATM.

**Closed by RomanGotsiy** 2019-05-09 12:09 UTC

**Comment by raderio** [comment] 2019-05-09 12:34
Oh, thanks. Any estimates when it will be available?

**Comment by RomanGotsiy** [comment] 2019-05-09 12:42
Pretty busy right now so, unfortunately, can't estimate.
