### ISSUE TITLE
redoc.module.ngfactory is not found

### ISSUE THREAD

**Issue by jroweboy** [Rebilly/ReDoc#117] opened 2016-09-21 18:51 UTC
I followed the instructions in the README, but it doesn't mention anything about calling `npm run ngc` in the instructions, so when I run the server, I get the error `Cannot find module './redoc.module.ngfactory'.` I'm not sure if this file is supposed to be autogenerated or not, but I found that running `npm run ngc` generated the `redoc.module.ngfactory.ts` file that was missing. I can submit a PR to fix that in the README, but I'm very new to angular development and I imagine if its supposed to be autogenerated then the real issue is fixing it so that it is.

**Comment by RomanGotsiy** [comment] 2016-09-27 21:36
@jroweboy, you were right, `./redoc.module.ngfactory` is autogenerated and is needed only for production build.
`npm run ngc` is run for production build [here](https://github.com/Rebilly/ReDoc/blob/master/package.json#L20)

The issues was caused by webpack config not respecting windows/*nix path separators difference

fixed via 79693e1b276225be256b5e5ea0db849f31c7b3a6

**Closed by RomanGotsiy** 2016-09-27 21:36 UTC
Labels: dev
