### ISSUE TITLE
Generate response sample based on model description

### ISSUE THREAD

**Issue by darklynx** [Rebilly/ReDoc#6] opened 2016-01-21 23:20 UTC
When response sample is not provided by API description (in Swagger format) it would be great to see automatically generated sample based on the model of response object instead of `Sample unavailable` message.

Something similar to what [Swagger UI](https://github.com/swagger-api/swagger-ui) does, see "Example value" in [Swagger UI demo](http://petstore.swagger.io/#!/pet/addPet).

**Comment by RomanGotsiy** [comment] 2016-01-22 18:27
I'm showing this message only in cases [json-schema-instantiator](https://github.com/tomarad/JSON-Schema-Instantiator) fails to automatically generate sample.
I've tried latest ReDoc on petstore spec and latest Rebilly spec and I can't reproduce the issue.

@darklynx can you provide me with some details?

**Comment by darklynx** [comment] 2016-01-22 18:44
I tried it with models from my collection: https://github.com/darklynx/swagger-api-collection/tree/master/api/json for example Instagram API
Swagger UI is able to handle them, but I could imagine that there might be some issues with API description.

**Comment by darklynx** [comment] 2016-01-22 19:23
This is quite [simple model](https://raw.githubusercontent.com/darklynx/request-baskets/master/doc/api-swagger.json), yet ReDoc fails to parse / reconstruct request and response objects from definitions.

**Comment by RomanGotsiy** [comment] 2016-01-22 20:22
> ReDoc model objects always declare: "type": "object", this is omitted in my definitions

Actually according to the [JsonSchema spec](http://json-schema.org/latest/json-schema-validation.html#anchor8) omitting `"type": "object"` leads the schema to validate against anything (string, number, bool, etc).

Here is the quote from the spec:
> Some validation keywords only apply to one or more primitive types. When the primitive type of the instance cannot be validated by a given keyword, validation for this keyword and instance SHOULD succeed.

You can check this with any online JsonSchema validator by specifying schema without `type` field and trying to validate it against `number`, `bool`, `array`. It will be validated successfully.

So I don't know how this example should look like. I don't like showing incorrect example as SwaggerUI does as well
Anyway I believe I should show more descriptive message instead of `Sample unavailable` or write warnings to console or even throw error. @darklynx do you have any suggestions?

**Comment by darklynx** [comment] 2016-01-22 20:32
I could not find in Swagger 2.0 Spec, now [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) whether `"type"` is a mandatory property of "Schema Object" description or not. Although all examples from aforementioned document are declaring `"type": "object"` for complex types, I have seen a lot of Swagger examples where the `"type"` property is skipped, for example: 
* https://github.com/swagger-api/swagger-codegen/blob/master/samples/yaml/echo.yaml
* https://github.com/swagger-api/swagger-ui/blob/master/test/specs/v2/petstore.json

I'll take this into account and will always define `"type": "object"` for complex objects in my Swagger (OpenAPI) descriptions, nevertheless I recommend to fall-back to `"type": "object"` if one is not defined while parsing in ReDoc.

**Comment by darklynx** [comment] 2016-01-22 20:39
I would suggest (if this is technically possible) write a warning to console (or maybe even to the top of HTML document), yet fall-back to "type": "object" and generate example accordingly.

**Comment by RomanGotsiy** [comment] 2016-01-22 20:55
> I could not find in Swagger 2.0 Spec, now OpenAPI Specification whether "type" is a mandatory property of "Schema Object" description or not.

Yes you're right, It is not mandatory. But OpenAPI Specification declares that schema object is based on the JSON Schema Specification Draft 4. And JSON Schema Specification Draft 4 says that without specifying `type` schema should validate against anything (check out link and quote from my previous post)

Omitting `"type": "object"` is very common mistake. Even official OpenAPI examples [had this](https://github.com/OAI/OpenAPI-Specification/pull/462).

I didn't want to fallback silently to not appreciate this mistake. But I like your suggestion to show warning to the top of HTML document. So I think I'll do like this.

**Comment by darklynx** [comment] 2016-01-22 20:59
(y)

**Comment by darklynx** [comment] 2016-01-22 20:59
:+1:

**Comment by adamaltman** [comment] 2016-01-22 21:12
:+1:

**Comment by darklynx** [comment] 2016-01-22 21:55
@RomanGotsiy the [https://raw.githubusercontent.com/darklynx/swagger-api-collection/master/api/json/instagram.json](Instagram API) description looks really great now at http://rebilly.github.io/ReDoc/ can be used as a reference API to demonstrate the power of ReDoc ;)

**Comment by RomanGotsiy** [comment] 2016-01-23 15:33
@darklynx thanks! You're right, your spec looks much better than standard Petstore spec on ReDoc :+1: 
But I've found few issues with schema representation testing Redoc on this spec :blush:. I'll use this spec as a reference as soon as I fix these issues.

**Comment by RomanGotsiy** [comment] 2016-05-18 19:53
I've opened two other issues to track suggestion from this thread.
Closing this issue.

**Closed by RomanGotsiy** 2016-05-18 19:53 UTC
Labels: enhancement
