### ISSUE TITLE
x-logo as link

### ISSUE THREAD

**Issue by guydepauw** [Rebilly/ReDoc#642] opened 2018-09-13 07:35 UTC
I am using redoc-cli to create a zero-dependency html. Is there any way to wrap the image provided by x-logo into an a-href? I've tried adding it with beautifulsoup in the html-portion, but it doesn't seem to get rendered in the browser.

**Comment by RomanGotsiy** [comment] 2018-09-13 09:15
Duplicate of https://github.com/Rebilly/ReDoc/issues/627

**Closed by RomanGotsiy** 2018-09-13 09:15 UTC
