### ISSUE TITLE
»Array of« get prepended to discriminator

### ISSUE THREAD

**Issue by Houly** [Rebilly/ReDoc#397] opened 2017-12-21 09:14 UTC
The type of the property of the discriminator gets an »Array of« prepended when selecting a different type from the options. Here you can see the bug in action:

http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/Houly/0243f2977f5b889253632d83bf1ac4b0/raw/64ac5e811fc846e5303f22c32e6df5437fa60ac5/swagger.yaml

Just change the type and an »Array of« gets prepended to the type of value. Changing the type again leaves the »Array of« in place.

**Comment by RomanGotsiy** [comment] 2017-12-25 13:27
omg 😱... Thanks for this bug-report. This is the complex issue caused by wrong decisions I made writing 1.x.x ReDoc. In 2.x.x version which is in alpha yet, this issue is fixed. Unfortunately, I won't fix it for 1.x.x version. So, please wait for 2.x.x to be released.

Thanks again for bug-report with repro!

**Closed by RomanGotsiy** 2017-12-25 13:27 UTC
