### ISSUE TITLE
Chrome menu clicking issue with scrollYOffset set

### ISSUE THREAD

**Issue by vflame** [Rebilly/ReDoc#650] opened 2018-09-19 20:05 UTC
The navigation menu in 2.0 alpha isn't working properly in Chrome (v 69) with the scrollYOffset is set.

Clicking the menu items just collapses them repeatedly. Appears as though it's misclicking. Works fine in firefox.

**Comment by RomanGotsiy** [comment] 2018-10-05 13:05
I can't reproduce it.
Could you please share a minimal reproducible setup?

**Comment by RomanGotsiy** [comment] 2018-10-18 09:12
Closing as "Can't reproduce"

**Closed by RomanGotsiy** 2018-10-18 09:12 UTC
Labels: bug

**Comment by m-mohr** [comment] 2018-11-19 11:56
I have the same or a similar problem. Here is an example: https://open-eo.github.io/openeo-api/v/0.4.0/apireference Since some days I can't open the menu on the left properly, it was working for weeks properly. Seems a little like it clicks a little higher than actually clicked and opens wrong menu groups or doesn't open at all.

**Comment by RomanGotsiy** [comment] 2018-11-19 13:43
![image](https://user-images.githubusercontent.com/3975738/48710709-e4154b00-ec11-11e8-95b9-808bdd0ef227.png)

**Comment by m-mohr** [comment] 2018-11-19 13:45
@RomanGotsiy Sorry, there was a slash missing at the end - didn't know GitHub doesn't like that. See https://open-eo.github.io/openeo-api/v/0.4.0/apireference/

**Comment by m-mohr** [comment] 2018-12-06 13:15
@RomanGotsiy I think I found the issue. The problem occurs if you specify an element for the scrollYOffset which `el.getBoundingClientRect().bottom` returns a non-integer number for. It seems that in some places it works on integers and in some on floating point numbers. Using Math.ceil or Math.round in normalizeScrollYOffset solves the problem for me. So I'd suggest only allowing integers as scrollYOffset and ensure in code that it is always an integer.
