### ISSUE TITLE
tags with x-traitTag: true are now greyed out in redoc ouput

### ISSUE THREAD

**Issue by andrewjtech123** [Rebilly/ReDoc#194] opened 2017-02-01 18:02 UTC
I had to remove some content from my swagger.yaml file and now tags with `x-traitTag: true` are greyed out in redoc left navigation. 

https://andrewjtech123.github.io/rebilly-validschema/

**Comment by andrewjtech123** [comment] 2017-02-01 18:05
and if i scroll to bottom of page, the page freezes and redoc display issues start to occur

**Comment by RomanGotsiy** [comment] 2017-02-01 18:23
I can't reproduce it on the link you sent

**Comment by andrewjtech123** [comment] 2017-02-01 18:29
try now please

**Comment by andrewjtech123** [comment] 2017-02-01 18:29
also what is meant by x-traitTag is deprecated from the change log

![x-traittag deprecated](https://cloud.githubusercontent.com/assets/6719991/22520500/84796008-e882-11e6-92d3-68a3bff1769d.png)

**Comment by RomanGotsiy** [comment] 2017-02-01 18:37
@andrewjtech123 can reproduce the issue now.
A new release is planned for tomorrow or Friday.
Will try to include fix for this issue

**Comment by RomanGotsiy** [comment] 2017-02-01 18:38
`x-traitTag` deprecation is now reconsidered. I will remove deprecated warning in the next release

**Comment by andrewjtech123** [comment] 2017-02-01 18:53
Thank you ! For now we are removing all tags with x-traitTag and just using Level 1 headings in Description.  But this is not ideal as we lose the ability to control where in the left navigation we would like to place the tag content.

**Comment by RomanGotsiy** [comment] 2017-02-02 22:07
fixed with the latest version (v1.8.0):
http://rebilly.github.io/ReDoc/?url=https://andrewjtech123.github.io/rebilly-validschema/swagger.json

**Closed by RomanGotsiy** 2017-02-02 22:07 UTC
Labels: bug, ready
