### ISSUE TITLE
Expand all by default

### ISSUE THREAD

**Issue by karlismelderis** [Rebilly/ReDoc#593] opened 2018-08-06 08:01 UTC
Can you please add an option to generate file where all responses are expanded by default?
I think it duplicates this -https://github.com/Rebilly/ReDoc/issues/211

Problem is that we still need to provide PDF file of spec (due to internal procedures) and it's painful to click through API spec and expand all before saving to PDF :)

**Comment by karlismelderis** [comment] 2018-08-06 08:28
just to clarify I'm looking to expand both "Responses" and "Response Samples"
Response samples might be trickiest as all samples need to be visible

**Comment by jsamr** [comment] 2018-08-14 17:37
@karlismelderis In the meantime, you can just do:

``` javascript
document.querySelectorAll('div').forEach((div) => div.click())
```
in the browser console.

**Comment by SaraivaDaniel** [comment] 2018-12-19 13:34
I also have the need to expand all elements in the response schema (not examples). I tried the comment by @jsamr above, but it only expanded first level. 

To expand all definitions, I've included the following script after redoc initialization:

```javascript
// inspired by https://gist.github.com/stephenorem/5162a871c5d96bfa522e31ede6205e51
function getMaxDepth(elem) {
  var maxDepth = 0,
	  d,
	  parents;
	  
  document.querySelectorAll(elem).forEach((e) => {
	parents = getParents(e);
	d = parents ? parents.length + 1 : 1;
	maxDepth = d > maxDepth ? d : maxDepth;
  });

  return maxDepth;
}
	
// https://gomakethings.com/how-to-get-all-parent-elements-with-vanilla-javascript/
var getParents = function (elem) {
	// Set up a parent array
	var parents = [];
	
	// Push each parent element to the array
	for ( ; elem && elem !== document; elem = elem.parentNode ) {
		parents.push(elem);
	}
	
	// Return our parent array
	return parents;
};
	
document.querySelectorAll('div').forEach((div) => div.click());
max = getMaxDepth('td');
setTimeout(function() {
	for (i = 0; i <= max; i++) {
		document.querySelectorAll('tr:not(.expanded) > td').forEach((td) => td.click());
	}
}, 1000); 
// the timeout above is needed to let the divs be expanded first (didn't care to figure out right now why)
```

**Comment by naugtur** [comment] 2019-05-06 12:47
Here's a version that works to expand all arrows in definitions regardless of classes (mine had them obfuscated)

```js
setInterval(()=>{Array.from(document.querySelectorAll('table svg')).forEach(arr=>{
  if(!arr.tapped){
    arr.tapped=1
    arr.parentNode.click()
  }
})},1000)
```

**Comment by RomanGotsiy** [comment] 2019-05-12 19:46
Duplicate of #211 

note that you can expand all responses by using `expandResponses: "all`` setting.
There is no corresponding option for schemas yet though.

**Closed by RomanGotsiy** 2019-05-12 19:46 UTC

**Comment by benbro** [comment] 2019-05-15 19:43
What's the difference between expand all responses and expand schemas? Isn't the schema part of the response?

I've tried adding expand-responses="all" to the redoc tag but the items array inside my response example  is still collapsed:
```html
<redoc spec-url="openapi.yaml" expand-responses="all"></redoc>
```

**Comment by RomanGotsiy** [comment] 2019-05-16 06:04
Collapsed responses:

![image](https://user-images.githubusercontent.com/3975738/57830044-8c6b2d00-77b9-11e9-8963-58cdd889ddfa.png)


Expanded Responses with collapsed subschemas:

![image](https://user-images.githubusercontent.com/3975738/57830056-9856ef00-77b9-11e9-9f15-84221f43344b.png)


Expanded Responses with expanded subschemas:

![image](https://user-images.githubusercontent.com/3975738/57830073-a3aa1a80-77b9-11e9-8a83-3d3070152fee.png)

**Comment by bohnman** [comment] 2019-11-14 16:15
None of this solutions seem to expand deeply nested schemas.  My solution is the following:

```javascript
    var expandInterval = setInterval(function() {
        document.querySelectorAll('tr:not(.expanded) > td').forEach((td) => td.click())
    }, 100);

    setTimeout(function() {
        clearInterval(expandInterval)
    }, 3000);
```

**Comment by rhatfield-bushel** [comment] 2020-03-12 18:35
Here's what I think is a slightly more elegant solution, figured I'd share. It's still a work around, but it doesn't cause any visible expanding, and updates when `oneOf` sections change.

This works in an almost recursive fashion, with each click event causing a mutation and in turn another click event (and so on).

One slight side effect, the schema sections are no longer collapsable, but for my purposes that's acceptable.

```html
<redoc></redoc>
<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"></script>
<script>
  var expand = () => {
    // this likely could be narrowed, but this finds all table cells,
    // and clicks them just in case.
    document
      .querySelectorAll("tr:not(.expanded) > td")
      .forEach(td => td.click());
  };

  var observe = ({ elements, action, types }) => {
    var ddObserver = new MutationObserver(mutations => action(mutations));
    elements.forEach(dd => ddObserver.observe(dd, types));
  };

  var onLoadCallback = err => {
    // first, watch all buttons to see when the selection changes
    // then, watch the table and expand all subitems
    var observables = [
      {
        elements: document.querySelectorAll(
          ".api-content>div>div>div>div>ul>li"
        ),
        action: mutations => mutations.forEach(m => expand()),
        types: {
          attributes: true
        }
      },
      {
        elements: document.querySelectorAll(
          ".api-content>div>div>div>div>table"
        ),
        action: expand,
        types: {
          attributes: true,
          subtree: true
        }
      }
    ];

    observables.forEach(o => observe(o));

    // once for good measure
    expand();
  };

  Redoc.init(
    "openapi.yaml",
    {
      jsonSampleExpandLevel: "all"
    },
    document.querySelector("redoc"),
    onLoadCallback
  );
</script>
```

**Comment by thim81** [comment] 2021-01-14 22:39
@RomanHotsiy 

How can you configure the `Expanded Responses with expanded subschemas`?

By setting the to `expandResponses: "all" `or `expandResponses: "200,201,422"`, it is not expendaning the subschema's like in your screenshot?

Is there another setting that can be used for this?

**Comment by enihsyou** [comment] 2021-01-24 10:02
Thanks to  https://github.com/Redocly/redoc/issues/593#issuecomment-553960721 I have the following solution.
It works on 2.0.0-rc.48 (right now), and narrows down to `button`.
```javascript
// find all expandable button and click on it
const expandInterval = setInterval(() => document
    .querySelectorAll('tr:not(.expanded) > td > button[aria-label*=expand]')
    .forEach((btn) => btn.click()), 100);

// click repeatedly for 1 second, that roughly 10 levels.
setTimeout(() => clearInterval(expandInterval), 1000);
```
Wrap this in a `script` tag and append at the end of HTML `body` tag and it works perfectly.

**Comment by tothdaniel** [comment] 2022-05-26 14:54
Actually the previous solution expands almost everyting except the payloads since they are in a different html sctucture (ul, li, etc.). Removing these specific parts from the selector solves the issue and expands everyting, tested on 2.0.0-rc.63.

````javascript
// find all expandable button and click on it
const expandInterval = setInterval(() => document
    .querySelectorAll('button[aria-label*=expand]')
    .forEach((btn) => btn.click()), 100);


// click repeatedly for 1 second, that roughly 10 levels.
 setTimeout(() => clearInterval(expandInterval), 1000);
````

**Comment by jfoclpf** [comment] 2022-12-19 19:59
@jsamr is not that wise clicking in every div, you cal filter by button and content

To collapse all

```js
document.querySelectorAll('button').forEach(btn => {
    if(btn.innerHTML.includes('Collapse all')) btn.click()
})
```

To expand all

```js
document.querySelectorAll('button').forEach(btn => {
    if(btn.innerHTML.includes('Expand all')) btn.click()
})
```
