### ISSUE TITLE
allOf not working properly within array items

### ISSUE THREAD

**Issue by joostfarla** [Rebilly/ReDoc#136] opened 2016-11-04 16:16 UTC
This works correctly:

```yaml
responses:
  '200':
    description: OK
    schema:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: 'someDefinition.yaml'
```

This initially loads fine, but gives an error (Can't load schema at ..) when trying to expand the `data` element in the response schema:

```yaml
responses:
  '200':
    description: OK
    schema:
      type: object
      properties:
        data:
          type: array
          items:
            allOf:
              - $ref: 'someDefinition.yaml
              - xml
                  name: foo
```

The schema example on the right side seems to render correctly.

**Comment by RomanGotsiy** [comment] 2016-11-04 22:24
@joostfarla, Thanks for reporting. I was able to reproduce the issue.
The fix shouldn't take so much time so most likely it will be included in the next minor release.

**Comment by joostfarla** [comment] 2016-11-05 08:44
@RomanGotsiy Awesome! 👍

**Comment by RomanGotsiy** [comment] 2016-11-05 14:09
Fixed, will be ready for use in the next minor release which will be released at the beginning of the next week

**Closed** 2016-11-05 14:08 UTC
Labels: bug

**Comment by joostfarla** [comment] 2016-11-07 13:37
Thanks for the fix! I've now actually found more scenarios where this causes failure. 

For example the following HAL response:

```
get:
  summary: GET /datasets
  responses:
    '200':
      description: OK
      schema:
        allOf:
          - $ref: 'Collection.yaml'
          - type: object
            required:
              - _embedded
            properties:
              _embedded:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: 'Dataset.yaml'
```

**Collection.yaml**

```
type: object
required:
  - totalItems
  - _links
properties:
  totalItems:
    type: integer
    format: int32
  _links:
    type: object
    required:
      - next
    properties:
      next:
        type: object
        required:
          - href
        properties:
          href:
            type: string
```

**Dataset.yaml**

```
type: object
required:
  - id
  - name
properties:
  id:
    type: string
  name:
    type: string
```

Can you take a look at this?

**Comment by joostfarla** [comment] 2016-11-25 11:51
@RomanGotsiy did you already had the chance to look at this issue? I don't mean to rush, but I'm presenting stuff next week, and it would be awesome if I have a fully working doc page.  👍

**Comment by RomanGotsiy** [comment] 2016-11-25 13:05
@joostfarla yes, sorry for delay. I've been working on other things. Will publish new release on weekends

**Comment by RomanGotsiy** [comment] 2016-11-28 19:01
@joostfarla new version `v1.5.2` has been just released.
Let me know if it the issue is solved for you know

**Comment by joostfarla** [comment] 2016-11-29 06:24
Works like a charm! Thanks!! 👍
