### ISSUE TITLE
Response Headers Title is Rendered Below Actual Headers

### ISSUE THREAD

**Issue by tbrunia** [Rebilly/ReDoc#509] opened 2018-05-27 15:21 UTC
![image](https://user-images.githubusercontent.com/9560078/40587591-d95b8df6-6196-11e8-8fc1-28e3058c7b75.png)

I'm using the React component version: 2.0.0-alpha.20. The response header title is appearing below the response headers.

I think my Open API response is well structured...

```
...
        "responses": {
          "204": {
            "description": "Successful operation",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Location": {
                "schema": {
                  "type": "string"
                },
                "description": "A url pointing to the location of the created or updated thing. Can be used to retrieve the thing."
              }
            },
...
          }
        },
...
```

Live example:
https://beta.docs.xilution.com/elements/data-accessor
Select Things > Create or Update a Thing > 204 Successful operation

**Comment by RomanGotsiy** [comment] 2018-05-28 07:52
It seems to be caused by `https://stackpath.bootstrapcdn.com/bootstrap/scss/_reboot.scss` used in your site. It sets css `caption-side: bottom;` for all the tables (I've never known about this css rule before 😯)

I will add fix for this into ReDoc but a quick workaround would be to add the following css to your site css:

```css
.redoc-wrap table {
  caption-side: top;
}
```

**Closed** 2018-05-28 18:55 UTC

**Comment by tbrunia** [comment] 2018-05-28 23:43
Thanks!
