### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by jeff-matthews** [Rebilly/ReDoc#169] opened 2016-12-19 20:14 UTC
The following **unmet peer dependencies** seem to be causing `npm start` errors after cloning the repo and running `npm install`:

- npm WARN string-replace-webpack-plugin@0.0.4 requires a peer of webpack@^1.4.2 but none was installed.
- npm WARN codelyzer@2.0.0-beta.3 requires a peer of tslint@~4.0.0 but none was installed.
- npm WARN karma-coverage@0.2.6 requires a peer of istanbul@~0.3.0 but none was installed.
- npm WARN @angular/core@2.3.1 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
- npm WARN @angular/core@2.3.1 requires a peer of zone.js@^0.7.2 but none was installed.

Running `npm install` produces several [errors.txt](https://github.com/Rebilly/ReDoc/files/661967/errors.txt) and prevents redoc from rendering swagger.yaml locally.

Manual installation works for **istanbul** and **tslint** only, but not the remaining dependencies.

ReDoc v1.6.2
node v6.9.2
Mac OS X v10.11.6

Chrome browser console log 
[localhost-1482178647617.txt](https://github.com/Rebilly/ReDoc/files/662046/localhost-1482178647617.txt)

**Comment by RomanGotsiy** [comment] 2016-12-19 20:23
Seems to be an issue with `awesome-typescript-loader`: https://github.com/s-panferov/awesome-typescript-loader/issues/190

Will try to update deps and stick them to working versions

**Comment by RomanGotsiy** [comment] 2016-12-19 20:45
@jeff-matthews try now and let me know if it works for you.

Before try, remove and install all node_modules

**Comment by RomanGotsiy** [comment] 2016-12-19 20:51
seems it was the same as #168. The author of #168 confirms the issue has been fixed.

Closing this issue so far. Feel free to reopen if the issue is not resolved for you

**Comment by jeff-matthews** [comment] 2016-12-19 21:51
thanks @RomanGotsiy. I'm able to run `npm start` without errors and render swagger.yaml locally. 

Interestingly, I'm still getting warnings about unmet peer dependencies on `npm install`, which may be a problem for continuous integration (CI) unless I can modify my CI build script to ignore the warnings.

**Comment by RomanGotsiy** [comment] 2016-12-19 22:32
These warnings are not critical. I will fix them in the future

**Closed by RomanGotsiy** 2016-12-19 22:32 UTC

**Comment by seanpk** [comment] 2017-02-08 20:16
@RomanGotsiy - I'd like to see the peer dependency warnings fixed on `npm install` too.
How were you thinking to solve this?

I wish there were peer dependencies for development in the `package.json` spec :-)

**Comment by RomanGotsiy** [comment] 2017-02-08 20:26
@seanpk let me know what are the warnings you see and which `npm` version you use.

I have `npm@4.0.5` and just did `rm -rf node_modules && npm install` and can't see any warnings.

**Comment by seanpk** [comment] 2017-02-08 20:42
```
$ npm -v && npm i redoc
3.10.10
foo@0.0.2 /Users/sean/Development/canary/api-canary-app
├── UNMET PEER DEPENDENCY @angular/common@^2.4.5
├── UNMET PEER DEPENDENCY @angular/compiler@^2.4.5
├── UNMET PEER DEPENDENCY @angular/core@^2.4.5
├── UNMET PEER DEPENDENCY @angular/platform-browser@^2.4.5
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@^2.4.5
├── UNMET PEER DEPENDENCY @angular/platform-server@^2.4.5
├── UNMET PEER DEPENDENCY core-js@^2.4.1
├─┬ redoc@1.8.0
│ └── mark.js@8.8.3  (git://github.com/julmot/mark.js.git#d4977c66c333275c4de665007ea7afae88286f0a)
├── UNMET PEER DEPENDENCY rxjs@^5.0.1
└── UNMET PEER DEPENDENCY zone.js@^0.7.2

npm WARN redoc@1.8.0 requires a peer of @angular/common@^2.4.5 but none was installed.
npm WARN redoc@1.8.0 requires a peer of @angular/compiler@^2.4.5 but none was installed.
npm WARN redoc@1.8.0 requires a peer of @angular/core@^2.4.5 but none was installed.
npm WARN redoc@1.8.0 requires a peer of @angular/platform-browser@^2.4.5 but none was installed.
npm WARN redoc@1.8.0 requires a peer of @angular/platform-browser-dynamic@^2.4.5 but none was installed.
npm WARN redoc@1.8.0 requires a peer of @angular/platform-server@^2.4.5 but none was installed.
npm WARN redoc@1.8.0 requires a peer of core-js@^2.4.1 but none was installed.
npm WARN redoc@1.8.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN redoc@1.8.0 requires a peer of zone.js@^0.7.2 but none was installed.
$
```

**Comment by RomanGotsiy** [comment] 2017-02-08 20:58
hmm, its strange as these dependencies are listed both in `devDependencies` and `peerDependencies` in `package.json`: https://github.com/Rebilly/ReDoc/blob/master/package.json#L50-L56

I will investigate

**Comment by seanpk** [comment] 2017-02-08 21:01
when I install the redoc package into my own project, doesn't `npm` install it in "production" mode?
