### ISSUE TITLE
Redoc Standalone not working in IE 11

### ISSUE THREAD

**Issue by ericksonlbs** [Rebilly/ReDoc#785] opened 2019-01-15 11:44 UTC
Hi, i am try to use the Redoc Standalone, using the below code not working in IE 11.

```

<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>
```

This error:
```

Something went wrong...
 Função incorreta.  
Stack traceError: Função incorreta.

   at e.exports (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:84:98972)
   at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:107:56850)
   at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:113:26410)
   at t.prototype.makeStore (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:107:60562)
   at t.prototype.render (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:107:61426)
   at ci (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:68:59690)
   at li (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:68:59540)
   at di (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:68:63191)
   at Vi (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:68:78330)
   at Qi (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:68:78710)

 ReDoc Version: 2.0.0-rc.0 
 Commit: a47a4b8
```

I need to do something?

Obs.: This error is when opened in local file, for example: c:\testApi.html. If opened in server it's working, for example: 'http://localhost/testeApi.html'.

**Comment by RomanGotsiy** [comment] 2019-01-17 10:21
It's duplicate of https://github.com/Rebilly/ReDoc/issues/149

**Closed by RomanGotsiy** 2019-01-17 10:21 UTC
