### ISSUE TITLE
ReDoc freezes 

### ISSUE THREAD

**Issue by arodoni** [Rebilly/ReDoc#182] opened 2017-01-13 23:50 UTC
In the following pages, when you scroll down to the bottom where the footer is, the page freezes. You can also make it freezes by clicking the "end" key.

https://www.zuora.com/developer/order-api/
https://www.zuora.com/developer/api-reference/

Has anyone encounter this issue and can offer a workaround?

Thank you, in advance!

**Comment by RomanGotsiy** [comment] 2017-01-14 09:06
@arodoni you're using `1.6.0-beta.perf` version.
I expect this issues to be fixed on the latest version due to recent side-menu refactor done.
Try please if this issue is reproducible on the latest version.

**Comment by arodoni** [comment] 2017-01-14 16:48
Thank you for your reply!
Is 1.7.0 the version we should try? Your github readme says not to use in
production. Is it stable enough to use in our live doc site?

[image: Inline image 1]

**Comment by RomanGotsiy** [comment] 2017-01-14 22:23
@arodoni you've misunderstood readme message. It says not to use `latest` release from CDN ( `https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js`) because it is updated automatically which each release and may include breaking changes.
It is absolutely OK to use concrete version `1.7.0` as it won't be changed so you can be sure your docs won't be broken until you manually update the version.

The latest version at the moment is `1.7.0`.

**Comment by arodoni** [comment] 2017-01-15 01:05
One more question. Does 1.7.0 include the lazy rendering and other
performance enhancements that you made?

Thank you very much for your assistance!

alex

**Comment by RomanGotsiy** [comment] 2017-01-15 07:40
yes, `1.7.0` includes all performance enhancements.

**Comment by RomanGotsiy** [comment] 2017-01-28 14:46
@arodoni does using latest fixed issue for you?

**Comment by arodoni** [comment] 2017-01-28 15:46
Yes, it did.

Thank you!

**Closed** 2017-01-28 15:51 UTC
