### ISSUE TITLE
Better error messages for diagnosis

### ISSUE THREAD

**Issue by natke** [Rebilly/ReDoc#113] opened 2016-09-16 01:06 UTC
When I try to render the documentation for my swagger.json spec, I get the following error:

Oops... ReDoc failed to render this spec

Unable to resolve $ref pointer 

It's a rather large specification and probably has an error in it, but I need some more information to locate the error (if there is one). Is it possible to get access to some more information about the error?

I tried to run the demo locally but could not run the following step:

npm run jspm-install

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "jspm-install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! missing script: jspm-install

**Comment by RomanGotsiy** [comment] 2016-09-16 02:50
@natke, yes this error message definitely should be improved.
I will check this.

Actually, this error message comes from tool I use for reference resolving so most likely your spec has some unresolvable references. Try to validate your spec using `editor.swagger.io`.

Regarding `npm run jspm-install`: it's not actual anymore, I just forgot to update steps. Thanks for reporting this.

**Comment by natke** [comment] 2016-09-16 16:03
Thanks for the quick reply.

Is the tool you talking about: https://www.npmjs.com/package/json-schema-ref-parser?

I ran the spec through the tool manually and it generated the resolved spec fine. But maybe I didn't exactly replicate the calls to this tool in the way that redoc is doing? Is it possible to summarize the API calls you are using?

**Comment by RomanGotsiy** [comment] 2016-09-17 13:38
@natke, would be great if you're able to provide me with a minimal reproducible spec or the actual spec you are trying to visualize with ReDoc?

**Comment by natke** [comment] 2016-09-17 17:35
Hi again, I did manage to get it working. I think the problem was that I was trying to serve a file. Once I served both my index.html and my spec over http it worked fine.

I think that error message is not actually from the parser - it is from your code, but it looks like there is an unresolved promise somewhere in the call chain. Might be worth looking into, and adding some better diagnostics and tests.

**Comment by RomanGotsiy** [comment] 2016-09-20 22:15
@natke, If you don't mind I will keep this issue open as it is not fixed: error messages sometimes are not clear

**Comment by natke** [comment] 2016-09-20 22:32
No problem - just wanted to indicate that I didn't have any further issues

**Comment by krsyoung** [comment] 2016-09-27 16:15
@natke curious if I'm getting the same thing you were.  What I was trying to do was run redoc with a local index.html and swagger file (i.e. just open them from the filesystem vs serving via HTTP).  Is this what you were originally doing when you received the error?

In my case I get a full error as: 
```
Unable to resolve $ref pointer "file:///tmp/instagram.yaml"
```

The HTML had:
```
<!DOCTYPE html>
<html>
<head>
  <title>API Docs</title>
  <!-- needed for mobile devices -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <redoc spec-url="instagram.yaml"></redoc>
  <script src="redoc.min.js"></script>
</body>
</html>
```

**Comment by natke** [comment] 2016-09-27 17:25
Yep, that's exactly what I saw

**Comment by pupi1985** [comment] 2016-11-09 22:44
This actually looks like a bug. Faced the same issue here doing the same thing.

```
Unhandled Promise rejection:
Error: Uncaught (in promise): SyntaxError: Unable to resolve $ref pointer "file:///path/to/my/file/swagger.json"
at l (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:45:23914)
at https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:45:24286
at t.invokeTask (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:45:29397)
at Object.onInvokeTask (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:11:1812)
at t.invokeTask (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:45:29333)
at n.runTask (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:45:26757)
at o (https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js:45:23374)
```
Same file is properly validated on the online editor. It is also properly displayed from a local web server, which has been my workaround so far.

**Comment by RomanGotsiy** [comment] 2016-11-12 10:04
@pupi1985 yes, I had a look at this and this is actually the issue.
The reason is that https://github.com/BigstickCarpet/json-schema-ref-parser doesn't support `file://` protocol.

I will fix this but this is not on the next-to-do queue coz this can be workarounded by simply running webserver

**Comment by RomanGotsiy** [comment] 2016-11-30 18:40
Will track this issue here: https://github.com/Rebilly/ReDoc/issues/149

Closing this as obsolete.

**Closed by RomanGotsiy** 2016-11-30 18:40 UTC
Labels: enhancement
